server:
    port: 9800
application:
    message: I am now here!!
    appname: and this is a SpringBoot App ...
security.basic.enabled: false
management.security.enabled: false

spring.data.mongodb.uri: mongodb://localhost:27000/test
